/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData lock = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData logo = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData message1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData moeny = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData order = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData share1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData alter = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData inforation = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData kefu = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe80e, fontFamily: _kFontFam);
}
